Update dependencies and migrate to AndroidX
MycroftAI/MycroftCore-Android pull request #11
Opened 2020-03-01 09:04 UTC by Stypox

At first I tried to build the app in Android Studio and it failed. I had to update Gradle and all of the dependencies to the latest version and now the app can compile and run on my phone. I also migrated to AndroidX (the support library is deprecated).
Even though I am not sure this PR will be useful, I decided to submit it anyway, who knows ;-)
I have not signed a CLA (Contributor Licensing Agreement)

2020-03-02 02:54 UTC, skraynick requested changes
All the .idea files should be excluded from the PR.. Thanks.. Please remove and check ignore file.

2020-03-03 19:22 UTC, Stypox commented
Done :-)

2020-03-04 22:24 UTC, skraynick commented
Funny, the .idea files are on the repo. I will double check the gitignore, something is not working. Thanks. Merging.

2020-03-04 22:24 UTC, skraynick approved these changes

2020-03-04 22:26 UTC, merged